/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JLabel;

/**
 *
 * @author david
 */
public class CartelaView extends javax.swing.JFrame {

    /**
     * Creates new form Cartela
     */
    public CartelaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        B1 = new javax.swing.JPanel();
        b1 = new javax.swing.JLabel();
        B2 = new javax.swing.JPanel();
        b2 = new javax.swing.JLabel();
        B6 = new javax.swing.JPanel();
        b6 = new javax.swing.JLabel();
        B7 = new javax.swing.JPanel();
        b7 = new javax.swing.JLabel();
        B11 = new javax.swing.JPanel();
        b11 = new javax.swing.JLabel();
        B16 = new javax.swing.JPanel();
        b16 = new javax.swing.JLabel();
        B21 = new javax.swing.JPanel();
        b21 = new javax.swing.JLabel();
        B12 = new javax.swing.JPanel();
        b12 = new javax.swing.JLabel();
        B17 = new javax.swing.JPanel();
        b17 = new javax.swing.JLabel();
        B22 = new javax.swing.JPanel();
        b22 = new javax.swing.JLabel();
        B3 = new javax.swing.JPanel();
        b3 = new javax.swing.JLabel();
        B8 = new javax.swing.JPanel();
        b8 = new javax.swing.JLabel();
        B13 = new javax.swing.JPanel();
        b13 = new javax.swing.JLabel();
        B18 = new javax.swing.JPanel();
        b18 = new javax.swing.JLabel();
        B23 = new javax.swing.JPanel();
        b23 = new javax.swing.JLabel();
        B4 = new javax.swing.JPanel();
        b4 = new javax.swing.JLabel();
        B9 = new javax.swing.JPanel();
        b9 = new javax.swing.JLabel();
        B14 = new javax.swing.JPanel();
        b14 = new javax.swing.JLabel();
        B19 = new javax.swing.JPanel();
        b19 = new javax.swing.JLabel();
        B24 = new javax.swing.JPanel();
        b24 = new javax.swing.JLabel();
        B5 = new javax.swing.JPanel();
        b5 = new javax.swing.JLabel();
        B10 = new javax.swing.JPanel();
        b10 = new javax.swing.JLabel();
        B15 = new javax.swing.JPanel();
        b15 = new javax.swing.JLabel();
        B20 = new javax.swing.JPanel();
        b20 = new javax.swing.JLabel();
        B25 = new javax.swing.JPanel();
        b25 = new javax.swing.JLabel();
        nomeDaCartela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B1.setBackground(new java.awt.Color(255, 255, 255));

        b1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 0));
        b1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1.setText("01");

        javax.swing.GroupLayout B1Layout = new javax.swing.GroupLayout(B1);
        B1.setLayout(B1Layout);
        B1Layout.setHorizontalGroup(
                B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        B1Layout.setVerticalGroup(
                B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(34, Short.MAX_VALUE))
        );

        B2.setBackground(new java.awt.Color(204, 204, 204));
        B2.setForeground(new java.awt.Color(204, 204, 204));

        b2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 0));
        b2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2.setText("02");

        javax.swing.GroupLayout B2Layout = new javax.swing.GroupLayout(B2);
        B2.setLayout(B2Layout);
        B2Layout.setHorizontalGroup(
                B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B2Layout.createSequentialGroup()
                                .addContainerGap(25, Short.MAX_VALUE)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
        );
        B2Layout.setVerticalGroup(
                B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B6.setBackground(new java.awt.Color(204, 204, 204));

        b6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 0, 0));
        b6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b6.setText("06");

        javax.swing.GroupLayout B6Layout = new javax.swing.GroupLayout(B6);
        B6.setLayout(B6Layout);
        B6Layout.setHorizontalGroup(
                B6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B6Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B6Layout.setVerticalGroup(
                B6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B6Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B7.setBackground(new java.awt.Color(255, 255, 255));

        b7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b7.setForeground(new java.awt.Color(0, 0, 0));
        b7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b7.setText("07");

        javax.swing.GroupLayout B7Layout = new javax.swing.GroupLayout(B7);
        B7.setLayout(B7Layout);
        B7Layout.setHorizontalGroup(
                B7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B7Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B7Layout.setVerticalGroup(
                B7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B7Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B11.setBackground(new java.awt.Color(255, 255, 255));

        b11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b11.setForeground(new java.awt.Color(0, 0, 0));
        b11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b11.setText("11");

        javax.swing.GroupLayout B11Layout = new javax.swing.GroupLayout(B11);
        B11.setLayout(B11Layout);
        B11Layout.setHorizontalGroup(
                B11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B11Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B11Layout.setVerticalGroup(
                B11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B11Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B16.setBackground(new java.awt.Color(204, 204, 204));

        b16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b16.setForeground(new java.awt.Color(0, 0, 0));
        b16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b16.setText("16");

        javax.swing.GroupLayout B16Layout = new javax.swing.GroupLayout(B16);
        B16.setLayout(B16Layout);
        B16Layout.setHorizontalGroup(
                B16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B16Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B16Layout.setVerticalGroup(
                B16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B16Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B21.setBackground(new java.awt.Color(255, 255, 255));

        b21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b21.setForeground(new java.awt.Color(0, 0, 0));
        b21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b21.setText("21");

        javax.swing.GroupLayout B21Layout = new javax.swing.GroupLayout(B21);
        B21.setLayout(B21Layout);
        B21Layout.setHorizontalGroup(
                B21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B21Layout.createSequentialGroup()
                                .addContainerGap(31, Short.MAX_VALUE)
                                .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
        );
        B21Layout.setVerticalGroup(
                B21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B21Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        B12.setBackground(new java.awt.Color(204, 204, 204));

        b12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b12.setForeground(new java.awt.Color(0, 0, 0));
        b12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b12.setText("12");

        javax.swing.GroupLayout B12Layout = new javax.swing.GroupLayout(B12);
        B12.setLayout(B12Layout);
        B12Layout.setHorizontalGroup(
                B12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B12Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B12Layout.setVerticalGroup(
                B12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B12Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B17.setBackground(new java.awt.Color(255, 255, 255));

        b17.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b17.setForeground(new java.awt.Color(0, 0, 0));
        b17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b17.setText("17");

        javax.swing.GroupLayout B17Layout = new javax.swing.GroupLayout(B17);
        B17.setLayout(B17Layout);
        B17Layout.setHorizontalGroup(
                B17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B17Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B17Layout.setVerticalGroup(
                B17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B17Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B22.setBackground(new java.awt.Color(204, 204, 204));

        b22.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b22.setForeground(new java.awt.Color(0, 0, 0));
        b22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b22.setText("22");

        javax.swing.GroupLayout B22Layout = new javax.swing.GroupLayout(B22);
        B22.setLayout(B22Layout);
        B22Layout.setHorizontalGroup(
                B22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B22Layout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
        );
        B22Layout.setVerticalGroup(
                B22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B22Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        B3.setBackground(new java.awt.Color(255, 255, 255));

        b3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 0));
        b3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b3.setText("03");

        javax.swing.GroupLayout B3Layout = new javax.swing.GroupLayout(B3);
        B3.setLayout(B3Layout);
        B3Layout.setHorizontalGroup(
                B3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B3Layout.createSequentialGroup()
                                .addContainerGap(26, Short.MAX_VALUE)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
        );
        B3Layout.setVerticalGroup(
                B3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B3Layout.createSequentialGroup()
                                .addContainerGap(34, Short.MAX_VALUE)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
        );

        B8.setBackground(new java.awt.Color(204, 204, 204));

        b8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b8.setForeground(new java.awt.Color(0, 0, 0));
        b8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b8.setText("08");

        javax.swing.GroupLayout B8Layout = new javax.swing.GroupLayout(B8);
        B8.setLayout(B8Layout);
        B8Layout.setHorizontalGroup(
                B8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B8Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B8Layout.setVerticalGroup(
                B8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B8Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B13.setBackground(new java.awt.Color(255, 255, 255));

        b13.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b13.setForeground(new java.awt.Color(0, 0, 0));
        b13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b13.setText("13");

        javax.swing.GroupLayout B13Layout = new javax.swing.GroupLayout(B13);
        B13.setLayout(B13Layout);
        B13Layout.setHorizontalGroup(
                B13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B13Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B13Layout.setVerticalGroup(
                B13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B13Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B18.setBackground(new java.awt.Color(204, 204, 204));

        b18.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b18.setForeground(new java.awt.Color(0, 0, 0));
        b18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b18.setText("18");

        javax.swing.GroupLayout B18Layout = new javax.swing.GroupLayout(B18);
        B18.setLayout(B18Layout);
        B18Layout.setHorizontalGroup(
                B18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B18Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B18Layout.setVerticalGroup(
                B18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B18Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B23.setBackground(new java.awt.Color(255, 255, 255));

        b23.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b23.setForeground(new java.awt.Color(0, 0, 0));
        b23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b23.setText("23");

        javax.swing.GroupLayout B23Layout = new javax.swing.GroupLayout(B23);
        B23.setLayout(B23Layout);
        B23Layout.setHorizontalGroup(
                B23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B23Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B23Layout.setVerticalGroup(
                B23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B23Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        B4.setBackground(new java.awt.Color(204, 204, 204));

        b4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 0, 0));
        b4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b4.setText("04");

        javax.swing.GroupLayout B4Layout = new javax.swing.GroupLayout(B4);
        B4.setLayout(B4Layout);
        B4Layout.setHorizontalGroup(
                B4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B4Layout.setVerticalGroup(
                B4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B4Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B9.setBackground(new java.awt.Color(255, 255, 255));

        b9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b9.setForeground(new java.awt.Color(0, 0, 0));
        b9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b9.setText("09");

        javax.swing.GroupLayout B9Layout = new javax.swing.GroupLayout(B9);
        B9.setLayout(B9Layout);
        B9Layout.setHorizontalGroup(
                B9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B9Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B9Layout.setVerticalGroup(
                B9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B9Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B14.setBackground(new java.awt.Color(204, 204, 204));

        b14.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b14.setForeground(new java.awt.Color(0, 0, 0));
        b14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b14.setText("14");

        javax.swing.GroupLayout B14Layout = new javax.swing.GroupLayout(B14);
        B14.setLayout(B14Layout);
        B14Layout.setHorizontalGroup(
                B14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B14Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B14Layout.setVerticalGroup(
                B14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B14Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B19.setBackground(new java.awt.Color(255, 255, 255));

        b19.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b19.setForeground(new java.awt.Color(0, 0, 0));
        b19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b19.setText("19");

        javax.swing.GroupLayout B19Layout = new javax.swing.GroupLayout(B19);
        B19.setLayout(B19Layout);
        B19Layout.setHorizontalGroup(
                B19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B19Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B19Layout.setVerticalGroup(
                B19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B19Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B24.setBackground(new java.awt.Color(204, 204, 204));

        b24.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b24.setForeground(new java.awt.Color(0, 0, 0));
        b24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b24.setText("24");

        javax.swing.GroupLayout B24Layout = new javax.swing.GroupLayout(B24);
        B24.setLayout(B24Layout);
        B24Layout.setHorizontalGroup(
                B24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B24Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b24, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B24Layout.setVerticalGroup(
                B24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B24Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B5.setBackground(new java.awt.Color(255, 255, 255));

        b5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b5.setForeground(new java.awt.Color(0, 0, 0));
        b5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b5.setText("05");

        javax.swing.GroupLayout B5Layout = new javax.swing.GroupLayout(B5);
        B5.setLayout(B5Layout);
        B5Layout.setHorizontalGroup(
                B5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B5Layout.createSequentialGroup()
                                .addContainerGap(26, Short.MAX_VALUE)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
        );
        B5Layout.setVerticalGroup(
                B5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B5Layout.createSequentialGroup()
                                .addContainerGap(34, Short.MAX_VALUE)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
        );

        B10.setBackground(new java.awt.Color(204, 204, 204));

        b10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b10.setForeground(new java.awt.Color(0, 0, 0));
        b10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b10.setText("10");

        javax.swing.GroupLayout B10Layout = new javax.swing.GroupLayout(B10);
        B10.setLayout(B10Layout);
        B10Layout.setHorizontalGroup(
                B10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B10Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))
        );
        B10Layout.setVerticalGroup(
                B10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B10Layout.createSequentialGroup()
                                .addContainerGap(34, Short.MAX_VALUE)
                                .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
        );

        B15.setBackground(new java.awt.Color(255, 255, 255));

        b15.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b15.setForeground(new java.awt.Color(0, 0, 0));
        b15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b15.setText("15");

        javax.swing.GroupLayout B15Layout = new javax.swing.GroupLayout(B15);
        B15.setLayout(B15Layout);
        B15Layout.setHorizontalGroup(
                B15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B15Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B15Layout.setVerticalGroup(
                B15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B15Layout.createSequentialGroup()
                                .addContainerGap(35, Short.MAX_VALUE)
                                .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
        );

        B20.setBackground(new java.awt.Color(204, 204, 204));

        b20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b20.setForeground(new java.awt.Color(0, 0, 0));
        b20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b20.setText("20");

        javax.swing.GroupLayout B20Layout = new javax.swing.GroupLayout(B20);
        B20.setLayout(B20Layout);
        B20Layout.setHorizontalGroup(
                B20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B20Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        B20Layout.setVerticalGroup(
                B20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B20Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        B25.setBackground(new java.awt.Color(255, 255, 255));

        b25.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        b25.setForeground(new java.awt.Color(0, 0, 0));
        b25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b25.setText("25");

        javax.swing.GroupLayout B25Layout = new javax.swing.GroupLayout(B25);
        B25.setLayout(B25Layout);
        B25Layout.setHorizontalGroup(
                B25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B25Layout.createSequentialGroup()
                                .addContainerGap(32, Short.MAX_VALUE)
                                .addComponent(b25, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
        );
        B25Layout.setVerticalGroup(
                B25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(B25Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(b25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(B16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(B13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(B14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(B15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(B12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(B16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(B20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(B21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(B22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(B24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(B25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(B23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        nomeDaCartela.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        nomeDaCartela.setForeground(new java.awt.Color(0, 0, 0));
        nomeDaCartela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeDaCartela.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 524, Short.MAX_VALUE)
                        .addComponent(nomeDaCartela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeDaCartela, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartelaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartelaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel B1;
    private javax.swing.JPanel B10;
    private javax.swing.JPanel B11;
    private javax.swing.JPanel B12;
    private javax.swing.JPanel B13;
    private javax.swing.JPanel B14;
    private javax.swing.JPanel B15;
    private javax.swing.JPanel B16;
    private javax.swing.JPanel B17;
    private javax.swing.JPanel B18;
    private javax.swing.JPanel B19;
    private javax.swing.JPanel B2;
    private javax.swing.JPanel B20;
    private javax.swing.JPanel B21;
    private javax.swing.JPanel B22;
    private javax.swing.JPanel B23;
    private javax.swing.JPanel B24;
    private javax.swing.JPanel B25;
    private javax.swing.JPanel B3;
    private javax.swing.JPanel B4;
    private javax.swing.JPanel B5;
    private javax.swing.JPanel B6;
    private javax.swing.JPanel B7;
    private javax.swing.JPanel B8;
    private javax.swing.JPanel B9;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b10;
    private javax.swing.JLabel b11;
    private javax.swing.JLabel b12;
    private javax.swing.JLabel b13;
    private javax.swing.JLabel b14;
    private javax.swing.JLabel b15;
    private javax.swing.JLabel b16;
    private javax.swing.JLabel b17;
    private javax.swing.JLabel b18;
    private javax.swing.JLabel b19;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b20;
    private javax.swing.JLabel b21;
    private javax.swing.JLabel b22;
    private javax.swing.JLabel b23;
    private javax.swing.JLabel b24;
    private javax.swing.JLabel b25;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JLabel nomeDaCartela;
    // End of variables declaration

    public JLabel getB1() {
        return b1;
    }

    public void setB1(JLabel b1) {
        this.b1 = b1;
    }

    public JLabel getB10() {
        return b10;
    }

    public void setB10(JLabel b10) {
        this.b10 = b10;
    }

    public JLabel getB11() {
        return b11;
    }

    public void setB11(JLabel b11) {
        this.b11 = b11;
    }

    public JLabel getB12() {
        return b12;
    }

    public void setB12(JLabel b12) {
        this.b12 = b12;
    }

    public JLabel getB13() {
        return b13;
    }

    public void setB13(JLabel b13) {
        this.b13 = b13;
    }

    public JLabel getB14() {
        return b14;
    }

    public void setB14(JLabel b14) {
        this.b14 = b14;
    }

    public JLabel getB15() {
        return b15;
    }

    public void setB15(JLabel b15) {
        this.b15 = b15;
    }

    public JLabel getB16() {
        return b16;
    }

    public void setB16(JLabel b16) {
        this.b16 = b16;
    }

    public JLabel getB17() {
        return b17;
    }

    public void setB17(JLabel b17) {
        this.b17 = b17;
    }

    public JLabel getB18() {
        return b18;
    }

    public void setB18(JLabel b18) {
        this.b18 = b18;
    }

    public JLabel getB19() {
        return b19;
    }

    public void setB19(JLabel b19) {
        this.b19 = b19;
    }

    public JLabel getB2() {
        return b2;
    }

    public void setB2(JLabel b2) {
        this.b2 = b2;
    }

    public JLabel getB20() {
        return b20;
    }

    public void setB20(JLabel b20) {
        this.b20 = b20;
    }

    public JLabel getB21() {
        return b21;
    }

    public void setB21(JLabel b21) {
        this.b21 = b21;
    }

    public JLabel getB22() {
        return b22;
    }

    public void setB22(JLabel b22) {
        this.b22 = b22;
    }

    public JLabel getB23() {
        return b23;
    }

    public void setB23(JLabel b23) {
        this.b23 = b23;
    }

    public JLabel getB24() {
        return b24;
    }

    public void setB24(JLabel b24) {
        this.b24 = b24;
    }

    public JLabel getB25() {
        return b25;
    }

    public void setB25(JLabel b25) {
        this.b25 = b25;
    }

    public JLabel getB3() {
        return b3;
    }

    public void setB3(JLabel b3) {
        this.b3 = b3;
    }

    public JLabel getB4() {
        return b4;
    }

    public void setB4(JLabel b4) {
        this.b4 = b4;
    }

    public JLabel getB5() {
        return b5;
    }

    public void setB5(JLabel b5) {
        this.b5 = b5;
    }

    public JLabel getB6() {
        return b6;
    }

    public void setB6(JLabel b6) {
        this.b6 = b6;
    }

    public JLabel getB7() {
        return b7;
    }

    public void setB7(JLabel b7) {
        this.b7 = b7;
    }

    public JLabel getB8() {
        return b8;
    }

    public void setB8(JLabel b8) {
        this.b8 = b8;
    }

    public JLabel getB9() {
        return b9;
    }

    public void setB9(JLabel b9) {
        this.b9 = b9;
    }


}
